name: aron_gradient_line
description: "Animated gradient line used as a divider in AppBar and more."
version: 1.1.0
homepage: https://aroncode.com
repository: https://github.com/arononak/aron_gradient_line
issue_tracker: https://github.com/arononak/aron_gradient_line/issues
documentation: https://arononak.github.io/aron_gradient_line/doc/api/index.html
license: MIT

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
